### ISSUE TITLE
YouToddlerMediaContent is different than defined Metadata Object

### ISSUE THREAD

**Issue by TheUsernameIsNotTaken** [cant0r/YouToddler#12]
The following implementation of metadata is different in multiple points, than it is defined in the documentation: 
https://github.com/cant0r/YouToddler/blob/e392604e1a3bea024abd476494c00d366e8360c5/src/Libs/YouToddler/Models/YouToddlerMediaContent.cs#L3-L12

[The Metadata Object Definition] (https://manhatten.atlassian.net/wiki/spaces/AT/pages/4063276/REST+API+interfaces#Metadata-Object)

For this issue either the definiton needs to be updated, the implementation needs to be modified or a new definition needs to be decised between the two definitions.

**Comment by cant0r** [comment]
Uhm, I believe the original task here was to convert the received JSON object (on the WebAPI side) to a format which is "human readable" to the users of the Frontend and we're going to send that friendly JSON to the Frontend to be processed.

Unfortunately I'm not aware of us accepting this decision anywhere. Due to our close deadline could you please transform this modell to the desired modell you shared ("The Metadata Object Definition") on the WebAPi side? @TheUsernameIsNotTaken

**Comment by cant0r** [comment]
Our compontents work with different modells at the different points of execution.

**Comment by TheUsernameIsNotTaken** [comment]
Succesfully created Metadata class object form returned objects.  https://github.com/cant0r/YouToddler/blob/1846627b89f445a0ba9414791bbae73e31f11e0d/src/YouToddlerWebAPI/src/main/java/io/swagger/api/MetaApiController.java#L144-L189
